/**
 * Baked snapshot of the EHC Inventory Log V2 sheet (read 2026-07-10 via the
 * Drive connector) — real SKUs, real prices, real Drive photo links. Used
 * only when the live CSV export isn't reachable (the sheet isn't shared
 * publicly yet). Rows are in the sheet's own column vocabulary so they run
 * through the exact same mapper as the live feed.
 */
export const snapshotRows: Record<string, string>[] = [
  {
    Timestamp: "2026-06-22",
    "Permanent SKU": "A1-MD-0003",
    "Item Name": "Columbia Willapa River shorts",
    Brand: "Columbia",
    Category: "Outdoor / Fishing Shorts",
    Size: "",
    Color: "",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$22.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-22",
    "Permanent SKU": "A1-MD-0004",
    "Item Name": "Patagonia Baggies shorts",
    Brand: "Patagonia",
    Category: "Outdoor Shorts",
    Size: "",
    Color: "",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$35.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-22",
    "Permanent SKU": "A1-MD-0006",
    "Item Name": "Forenza leather jacket",
    Brand: "Forenza",
    Category: "Leather Jacket",
    Size: "",
    Color: "",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$30.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Other",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-23",
    "Permanent SKU": "A1-MD-0012",
    "Item Name": "Stitch Beachwear tropical short-sleeve button-down shirt",
    Brand: "Stitch Beachwear",
    Category: "Hawaiian / Casual Button-Down Shirt",
    Size: "L",
    Color: "Cream / navy blue / turquoise / mustard",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$18.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-23",
    "Permanent SKU": "A1-MD-0014",
    "Item Name": "Under Armour HeatGear U Golf striped performance polo",
    Brand: "Under Armour",
    Category: "Performance Golf Polo Shirt",
    Size: "XL",
    Color: "White / light gray with green and yellow logo",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$22.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-23",
    "Permanent SKU": "A1-MD-0015",
    "Item Name": "Abercrombie & Fitch floral super-slim stretch short-sleeve button-up shirt",
    Brand: "Abercrombie & Fitch",
    Category: "Casual Button-Down Shirt",
    Size: "S",
    Color: "Dark navy / charcoal with muted floral print",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$18.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-24",
    "Permanent SKU": "A1-MD-0022",
    "Item Name": "Paper Crane ribbed cropped cardigan and camisole twinset",
    Brand: "Paper Crane",
    Category: "Cardigan & Tank Top Set / Twinset",
    Size: "M",
    Color: "Rust / burnt orange / terracotta",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$18.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Women's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-24",
    "Permanent SKU": "A1-MD-0024",
    "Item Name": "Tommy Hilfiger Custom Fit windowpane plaid long-sleeve button-down shirt",
    Brand: "Tommy Hilfiger",
    Category: "Casual / Dress Button-Down Shirt",
    Size: "L / 16 1/2-17",
    Color: "Navy with light blue and red",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$12.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-24",
    "Permanent SKU": "A1-MD-0026",
    "Item Name": "J.Crew red and blue gingham long-sleeve button-down shirt",
    Brand: "J.Crew",
    Category: "Casual Button-Down Shirt",
    Size: "L",
    Color: "Red / bright blue / burgundy",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$14.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-24",
    "Permanent SKU": "A1-MD-0029",
    "Item Name": "Under Armour HeatGear Alter Ego Superman loose-fit graphic T-shirt",
    Brand: "Under Armour",
    Category: "Athletic Graphic T-Shirt",
    Size: "M",
    Color: "Navy blue with red, yellow and gray",
    Condition: "Good pre-owned with graphic wear; final inspection required",
    "Realistic Sold Value": "$20.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-26",
    "Permanent SKU": "A2-MD-0033",
    "Item Name": "Judy Blue light-wash distressed ripped skinny jeans with raw hem",
    Brand: "Judy Blue",
    Category: "Distressed Skinny Jeans",
    Size: "9/29",
    Color: "Light blue",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$23.00",
    "Inventory Status": "Listed",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Women's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-26",
    "Permanent SKU": "A2-MD-0037",
    "Item Name": "Brooks Brothers 346 olive green cotton chino pants",
    Brand: "Brooks Brothers 346",
    Category: "Chino Pants / Casual Pants",
    Size: "W40/L30",
    Color: "Olive green",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$22.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-26",
    "Permanent SKU": "A2-MD-0038",
    "Item Name": "Columbia KM5080 black burgundy colorblock nylon windbreaker jacket",
    Brand: "Columbia Sportswear Company",
    Category: "Windbreaker Jacket / Lightweight Outerwear",
    Size: "Men's M",
    Color: "Black / burgundy / maroon",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$28.00",
    "Inventory Status": "Unlisted",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-26",
    "Permanent SKU": "A2-MD-0039",
    "Item Name": "SpaceX lavender-gray organic cotton full-zip hoodie",
    Brand: "SpaceX",
    Category: "Full-Zip Hoodie / Sweatshirt",
    Size: "L",
    Color: "Lavender-gray / light purple",
    Condition: "Pre-owned; needs final inspection and authenticity review",
    "Realistic Sold Value": "$35.00",
    "Inventory Status": "Needs Review",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Not Confirmed",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0044",
    "Item Name": "Levi's faded black denim trucker jacket",
    Brand: "Levi's",
    Category: "Denim Trucker Jacket / Jean Jacket",
    Size: "Approx. 18x19",
    Color: "Faded black / charcoal gray",
    Condition: "Good pre-owned; visible fading and final inspection required",
    "Realistic Sold Value": "$29.95",
    "Inventory Status": "Needs Review",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Other",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0045",
    "Item Name": "Lauren Ralph Lauren navy double-breasted gold-button blazer",
    Brand: "Lauren Ralph Lauren",
    Category: "Women's Blazer / Sport Coat",
    Size: "20W",
    Color: "Navy blue",
    Condition: "Pre-owned; needs lint removal and final inspection",
    "Realistic Sold Value": "$30.00",
    "Inventory Status": "Needs Review",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Other",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0046",
    "Item Name": "Brooks Brothers orange cotton quarter-zip pullover with striped trim",
    Brand: "Brooks Brothers",
    Category: "Quarter-Zip Pullover / Sweatshirt",
    Size: "S",
    Color: "Burnt orange / coral with navy and teal accents",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$28.00",
    "Inventory Status": "Poshmark Listed / eBay Pending",
    "Listing Platforms": "Poshmark",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0048",
    "Item Name": "Nautica white sailing windbreaker jacket with black stripe",
    Brand: "Nautica",
    Category: "Men's Windbreaker Jacket / Lightweight Outerwear",
    Size: "XL",
    Color: "White / ivory with black accents",
    Condition: "Pre-owned; cleaning and final inspection required",
    "Realistic Sold Value": "$34.00",
    "Inventory Status": "Poshmark Listed / eBay Pending",
    "Listing Platforms": "Poshmark",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0049",
    "Item Name": "Columbia red plaid stretch long-sleeve shirt with tags",
    Brand: "Columbia",
    Category: "Men's Long-Sleeve Button-Up Shirt",
    Size: "XXL",
    Color: "Red / burgundy / tan / navy",
    Condition: "New with tags; final inspection required",
    "Realistic Sold Value": "$32.00",
    "Inventory Status": "Listed",
    "Listing Platforms": "Poshmark / eBay",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-27",
    "Permanent SKU": "A2-MD-0050",
    "Item Name": "Fabletics men's black utility performance jogger pants",
    Brand: "Fabletics",
    Category: "Men's Athletic Jogger / Utility Cargo Pants",
    Size: "L",
    Color: "Black with turquoise accents",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$23.00",
    "Inventory Status": "Poshmark Listed / eBay Pending",
    "Listing Platforms": "Poshmark",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-28",
    "Permanent SKU": "A4-MD-0055",
    "Item Name": "DKNY gray blue micro-geometric button-up shirt",
    Brand: "DKNY",
    Category: "Patterned Button-Up Shirt",
    Size: "M",
    Color: "Gray with blue and white accents",
    Condition: "Good pre-owned; final inspection required",
    "Realistic Sold Value": "$10.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Tops",
    "White Photo Links":
      "https://drive.google.com/file/d/1WU0J4fsfoaakZNfJT94tBlmLOvkQdkc-/view https://drive.google.com/file/d/1dHxKpl3sNnxl-GBXHak3L8SDFyHDJO9l/view https://drive.google.com/file/d/1gEJ53gu7j1nNvOqAqyrp2nfNGQQ1K2t7/view https://drive.google.com/file/d/1LuizMLEXqs2VIFpThkxEBJCzSIK8Q_8g/view",
  },
  {
    Timestamp: "2026-06-29",
    "Permanent SKU": "A4-MD-0057",
    "Item Name": "Licensed Superman DC Comics distressed shield graphic T-shirt",
    Brand: "Superman / DC Comics licensed",
    Category: "Graphic T-Shirt",
    Size: "M",
    Color: "Navy blue with red and yellow graphic",
    Condition: "Pre-owned; full inspection required",
    "Realistic Sold Value": "$16.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-06-30",
    "Permanent SKU": "A4-MD-0061",
    "Item Name": "Grey's Anatomy by Barco royal blue snap-front scrub jacket",
    Brand: "Grey's Anatomy by Barco",
    Category: "Scrub Jacket / Warm-Up Jacket",
    Size: "M",
    Color: "Royal blue",
    Condition: "Pre-owned; visible lint; final inspection required",
    "Realistic Sold Value": "$14.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Women's Workwear / Scrubs",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-07-05",
    "Permanent SKU": "A5-MD-0084",
    "Item Name": "Visconti made in Italy black blazer",
    Brand: "Visconti",
    Category: "Men's Blazer / Sport Coat",
    Size: "",
    Color: "Black / very dark navy",
    Condition: "Pre-owned; visible lint/wrinkles; final inspection required",
    "Realistic Sold Value": "$30.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Jackets & Coats",
    "White Photo Links":
      "https://drive.google.com/file/d/1cWXXypimP2tpWyXTQTq3df8X-DPdOG3C/view https://drive.google.com/file/d/16WJmw2SKoYmfA_Ed1lkgmlVURZMEdPvr/view https://drive.google.com/file/d/1rPWeaOY_WOGgCbkMZKhYcmtC3idVDm8L/view https://drive.google.com/file/d/1LSgTNmJrhblE1x_5ktdeusq4HA1NQLk-/view https://drive.google.com/file/d/1XyuG6ZvJoaKaTjIXdp0vm7lOg6tQoo01/view https://drive.google.com/file/d/1h-g5X1v8vMhRiEQkuUk5GYKHwqIdbws5/view https://drive.google.com/file/d/16mV934YJZ_0bFZ8PSWWIt_SSHIlSxckl/view",
  },
  {
    Timestamp: "2026-07-05",
    "Permanent SKU": "A5-MD-0085",
    "Item Name": "Port Authority black gray colorblock full-zip windbreaker jacket",
    Brand: "Port Authority",
    Category: "Men's Windbreaker Jacket / Lightweight Outerwear",
    Size: "XL",
    Color: "Black / light gray",
    Condition: "Pre-owned; visible small front mark/flaw and final inspection required",
    "Realistic Sold Value": "18",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Jackets & Coats",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0086",
    "Item Name": "Hoka One One Bondi 8 black running shoes",
    Brand: "Hoka One One",
    Category: "Running Shoes",
    Size: "Women's 7B",
    Color: "Black",
    Condition: "Pre-owned; final exterior and sole inspection required",
    "Realistic Sold Value": "$45.00",
    "Inventory Status": "Sold",
    "Listing Platforms": "eBay",
    Department: "Women's Shoes",
    "White Photo Links":
      "https://drive.google.com/file/d/1Gnkc_4_gUq8AZ99_uh_ZC4yw-OLQ6jCf/view https://drive.google.com/file/d/1oCoVrS50fJWPcNJIgcllkHznMJFVFMCk/view https://drive.google.com/file/d/14NB3sFmWS1FilcowgTKy1I81Z14s5uAT/view https://drive.google.com/file/d/1A76xRvvnMYnu5xA7cQ1fDaXtcDQawVVo/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0088",
    "Item Name": "Chevrolet Chevy Power black graphic sweatshirt",
    Brand: "Chevrolet / GM licensed",
    Category: "Graphic Sweatshirt / Crewneck",
    Size: "L",
    Color: "Black / faded black",
    Condition: "Pre-owned; visible fading/wash wear; final inspection required",
    "Realistic Sold Value": "$18.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Tops",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0089",
    "Item Name": "Levi's 505 blue straight-leg jeans",
    Brand: "Levi's",
    Category: "Jeans / Denim Pants",
    Size: "36 x 34",
    Color: "Medium blue wash",
    Condition: "Pre-owned; visible fading/wash wear; final inspection required",
    "Realistic Sold Value": "$22.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0090",
    "Item Name": "L.L.Bean Classic Fit tan cotton jeans",
    Brand: "L.L.Bean",
    Category: "Jeans / Casual Pants",
    Size: "31 x 32",
    Color: "Tan / beige",
    Condition: "Pre-owned; visible small lower-leg mark; final inspection required",
    "Realistic Sold Value": "$20.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Bottoms",
    "White Photo Links": "",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0091",
    "Item Name": "Alchemist Supply Wear Co Upper Michigan embroidered crewneck sweater",
    Brand: "Alchemist Supply Wear Co.",
    Category: "Crewneck Sweater / Pullover",
    Size: "L",
    Color: "Tan / beige heather",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$20.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Tops",
    "White Photo Links":
      "https://drive.google.com/file/d/16YBmN1SxGRP62CC2Z05NcA2kBzfUxDpb/view https://drive.google.com/file/d/1ykUBLNaDEo1Pfl-NXGzUQvRaBiGxmCKH/view https://drive.google.com/file/d/1KR_Bx9azaegKV-CKUqy71MLAGAWjw2m7/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0092",
    "Item Name": "Red green textured sleeveless sweater vest",
    Brand: "",
    Category: "Sweater Vest",
    Size: "",
    Color: "Red / burgundy with dark green trim",
    Condition: "Pre-owned; brand, size and final inspection required",
    "Realistic Sold Value": "$12.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Women's Tops",
    "White Photo Links":
      "https://drive.google.com/file/d/1H7lJUX1Byw4zx75eDoTrE2IM1KN46m5g/view https://drive.google.com/file/d/1WmbjtCEQ6rquYzrj_df95XxVZGb8mJ4z/view https://drive.google.com/file/d/1Nb5tCB7DP_KZcwK6uR9eh75CtS_ocEvn/view https://drive.google.com/file/d/1JI40RUOMfBwfj3yHr0bVAQn-e3sBEW0D/view https://drive.google.com/file/d/1w0krnSq6fexzFvneDKFwdm9iHLb6ccof/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0093",
    "Item Name": "Grant Thomas navy plaid long-sleeve button-down shirt",
    Brand: "Grant Thomas",
    Category: "Long-Sleeve Button-Down Shirt",
    Size: "",
    Color: "Navy / blue with tan and white",
    Condition: "Pre-owned; size and final inspection required",
    "Realistic Sold Value": "$12.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Tops",
    "White Photo Links":
      "https://drive.google.com/file/d/1nbhcR6LwDfQ3fVU0vyXQ-4t8bubGNhtw/view https://drive.google.com/file/d/12PZB3CSd51j7Y8QSLew9Iy_6xqR7H2nz/view https://drive.google.com/file/d/10z16Nzlm0b3Y_GW3dza2oO7rzGtvBAeJ/view https://drive.google.com/file/d/1fzozgyFDKh_-sF3au-69afxYWcP9SPS5/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0094",
    "Item Name": "New Balance WVTRLB1 black pink running shoes",
    Brand: "New Balance",
    Category: "Running Shoes / Athletic Sneakers",
    Size: "Women's 8.5",
    Color: "Black / white / pink / blue",
    Condition: "Pre-owned; final exterior and sole inspection required",
    "Realistic Sold Value": "$24.00",
    "Inventory Status": "Listed / Posted",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Women's Shoes",
    "White Photo Links":
      "https://drive.google.com/file/d/1-kTdx5kvGBd2Z88_GzLGayrgHgMA_12p/view https://drive.google.com/file/d/1s7ZGGfQrFa2g4Nq4ZIr9CsAOYmE6jFMo/view https://drive.google.com/file/d/13dTCsPgPGn94_8z-YKlNrmISj74gYxKR/view https://drive.google.com/file/d/1EU--Uaes8JKWLo3ZiIRaaEYzGk4XvrAF/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0095",
    "Item Name": "Columbia black full-zip hooded fleece jacket",
    Brand: "Columbia Sportswear Company",
    Category: "Hooded Fleece Jacket / Full-Zip Hoodie",
    Size: "L",
    Color: "Black",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$24.00",
    "Inventory Status": "Deferred - Needs Photos / Not Posted",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Jackets & Coats",
    "White Photo Links":
      "https://drive.google.com/file/d/1IAA_CP1cZNaL1eACEOYM4m55d7WTEuMh/view https://drive.google.com/file/d/1Coiag0erhTkuewSvFXYdEWVPrJG8NeL6/view https://drive.google.com/file/d/1k0ZRghqS9X3A-tEzPsBirF8Sash_LlBL/view https://drive.google.com/file/d/1ZY0C7ustxCRZ2ijyxwqG2JyVvATG6B8i/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0096",
    "Item Name": "Wrangler beige khaki utility pants",
    Brand: "Wrangler",
    Category: "Men's Utility Pants / Casual Pants",
    Size: "44",
    Color: "Beige / khaki",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$20.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Bottoms",
    "White Photo Links":
      "https://drive.google.com/file/d/1MMquOIU62Wjv7nmMsA1Lyp1-f_2geziE/view https://drive.google.com/file/d/1H4QKVugs9qXCZ0CYogG8gOcixxsIhBHI/view https://drive.google.com/file/d/1N3DTh_-eISjngxwfPLVAoDhhedE69gGt/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0097",
    "Item Name": "Wrangler beige pleated khaki shorts",
    Brand: "Wrangler",
    Category: "Men's Shorts / Casual Shorts",
    Size: "44",
    Color: "Beige / khaki",
    Condition: "Pre-owned; final inspection required",
    "Realistic Sold Value": "$14.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Bottoms",
    "White Photo Links":
      "https://drive.google.com/file/d/1h9ROaxtksOswzKkNS12iqtipU8NEkvN1/view https://drive.google.com/file/d/1BrYuBykOeXxFhnH5WkiBUiyJzVmcWxjR/view",
  },
  {
    Timestamp: "2026-07-06",
    "Permanent SKU": "A5-MD-0098",
    "Item Name": "L.L.Bean purple vintage made in USA jacket",
    Brand: "L.L.Bean",
    Category: "Vintage Jacket / Lightweight Outerwear",
    Size: "",
    Color: "Purple",
    Condition:
      "Pre-owned; vintage made-in-USA detail from source description; final condition inspection required",
    "Realistic Sold Value": "$35.00",
    "Inventory Status": "Unlisted / Needs Review",
    "Listing Platforms": "Poshmark / eBay / Mercari",
    Department: "Men's Jackets & Coats",
    "White Photo Links":
      "https://drive.google.com/file/d/1lvBU9OzNQu2pbJlaDqSy1tKFh9U_948N/view https://drive.google.com/file/d/1CZfSy2ix_jY1qt2Dob0tMBFKeOyGnwwK/view https://drive.google.com/file/d/1KJ6h5piO5Ce15Y1hxoVSFoKUVO-M3IN8/view https://drive.google.com/file/d/17hHcgQPjB9WGpjrVa1MUEhJr9XgzcrzJ/view https://drive.google.com/file/d/1_9MDZkA8LEACTtOu3AFoUm9jGWHoyv9S/view https://drive.google.com/file/d/1VpvU4y2jxfkg6itvLXTSwp_zBCGutdpY/view",
  },
];
