import type { Product } from "./types";

/**
 * Local fallback catalog. Used whenever GOOGLE_SHEET_ID is not set, or the
 * live sheet fetch fails/returns empty — keeps the storefront demoable and
 * keeps `next build` working without network access to Sheets.
 */
export const sampleProducts: Product[] = [
  {
    sku: "RU-001",
    slug: "carhartt-detroit-jacket-vintage-blanket-lined",
    name: "Detroit Jacket — Blanket Lined",
    brand: "Carhartt",
    category: "Men",
    type: "Jacket",
    size: "L",
    condition: "9/10 — Like New",
    conditionScore: 9,
    originalPrice: 220,
    price: 78,
    description:
      "Vintage duck canvas Detroit jacket, blanket lined for cold drops. Barely worn, no fade on the collar, snaps all intact. This is the one that outlives you.",
    images: [],
    tags: ["STEAL", "RARE"],
    inStock: true,
  },
  {
    sku: "RU-002",
    slug: "nike-air-force-1-og-white",
    name: "Air Force 1 '07 — Triple White",
    brand: "Nike",
    category: "Unisex",
    type: "Sneakers",
    size: "US 9",
    condition: "8/10 — Light Wear",
    conditionScore: 8,
    originalPrice: 110,
    price: 42,
    description:
      "The uniform. Light creasing on the toe box, sole still crisp, laces swapped fresh. Cleaned and ready to ship same day.",
    images: [],
    tags: ["STEAL"],
    inStock: true,
  },
  {
    sku: "RU-003",
    slug: "levis-501-vintage-90s-medium-wash",
    name: "501 Vintage — '90s Medium Wash",
    brand: "Levi's",
    category: "Women",
    type: "Denim",
    size: "W28",
    condition: "8/10 — Light Wear",
    conditionScore: 8,
    originalPrice: 98,
    price: 36,
    description:
      "Actual '90s pair, not a reissue. Broken in exactly right, no rips, button fly intact. Redline selvedge peek at the cuff.",
    images: [],
    tags: ["RARE", "LAST ONE"],
    inStock: true,
  },
  {
    sku: "RU-004",
    slug: "the-north-face-1996-retro-nuptse",
    name: "1996 Retro Nuptse Vest",
    brand: "The North Face",
    category: "Unisex",
    type: "Outerwear",
    size: "M",
    condition: "9/10 — Like New",
    conditionScore: 9,
    originalPrice: 260,
    price: 95,
    description:
      "Down-filled, box-quilted, zero flat spots. One small mark on the interior tag, invisible when worn. Packs its own stuff sack.",
    images: [],
    tags: ["STEAL"],
    inStock: true,
  },
  {
    sku: "RU-005",
    slug: "adidas-firebird-track-jacket-y2k",
    name: "Firebird Track Jacket — Y2K",
    brand: "Adidas",
    category: "Women",
    type: "Track Jacket",
    size: "S",
    condition: "7/10 — Great",
    conditionScore: 7,
    originalPrice: 85,
    price: 28,
    description:
      "Full zip, tricolor stripes, the exact archive cut everyone's been asking for. Light pilling under the arms, nothing structural.",
    images: [],
    tags: [],
    inStock: true,
  },
  {
    sku: "RU-006",
    slug: "dickies-874-work-pant-double-knee",
    name: "874 Work Pant — Double Knee",
    brand: "Dickies",
    category: "Men",
    type: "Pants",
    size: "34x32",
    condition: "8/10 — Light Wear",
    conditionScore: 8,
    originalPrice: 45,
    price: 18,
    description:
      "Reinforced double-knee, straight leg, faded to a perfect charcoal. Hemmed once, clean stitch, no patches needed.",
    images: [],
    tags: ["STEAL"],
    inStock: true,
  },
  {
    sku: "RU-007",
    slug: "patagonia-retro-x-fleece-vintage",
    name: "Retro-X Fleece Vest",
    brand: "Patagonia",
    category: "Unisex",
    type: "Fleece",
    size: "M",
    condition: "9/10 — Like New",
    conditionScore: 9,
    originalPrice: 199,
    price: 74,
    description:
      "Deep pile fleece with the shell face, zero pilling. This is the one that gets stolen by a friend within a week — hide it well.",
    images: [],
    tags: ["RARE"],
    inStock: true,
  },
  {
    sku: "RU-008",
    slug: "champion-reverse-weave-hoodie-vintage",
    name: "Reverse Weave Hoodie",
    brand: "Champion",
    category: "Men",
    type: "Hoodie",
    size: "XL",
    condition: "7/10 — Great",
    conditionScore: 7,
    originalPrice: 70,
    price: 24,
    description:
      "Heavyweight loopback fleece, side panel construction, that vintage droop in the hood. Soft as it's ever going to get.",
    images: [],
    tags: [],
    inStock: true,
  },
  {
    sku: "RU-009",
    slug: "dr-martens-1460-black-smooth",
    name: "1460 Boot — Black Smooth",
    brand: "Dr. Martens",
    category: "Women",
    type: "Boots",
    size: "UK 6",
    condition: "8/10 — Light Wear",
    conditionScore: 8,
    originalPrice: 170,
    price: 58,
    description:
      "Already broken in so you don't have to be. Sole units full tread, leather conditioned, laces fresh. Yellow stitch intact.",
    images: [],
    tags: ["LAST ONE"],
    inStock: true,
  },
  {
    sku: "RU-010",
    slug: "stussy-8-ball-tee-vintage-print",
    name: "8-Ball Tee — Vintage Print",
    brand: "Stüssy",
    category: "Unisex",
    type: "T-Shirt",
    size: "L",
    condition: "6/10 — Signs of Wear",
    conditionScore: 6,
    originalPrice: 55,
    price: 16,
    description:
      "Cracked print, exactly the way it should be. One small hem fray, priced for it. This is a wear-it-in-immediately piece.",
    images: [],
    tags: ["STEAL"],
    inStock: false,
  },
];
